title: "Sakiru Akinpelu"
email: "sakiruakinpelu1@gmail.com"
description: "Data Analyst | Power BI & SQL Specialist | Transforming Raw Data into Actionable Insights"
url: "https://sakiruakinpelu.github.io"
baseurl: ""
